name: "udb"
seeds:
- "127.0.0.1:1107"
- "127.0.0.1:1108"
- "127.0.0.1:1109"
replica_count: 2

bind_ip:
- "0.0.0.0"
bind_port: 1107
advertise_port: 1107

security:
  secret: "abcdef0123456789"

storage:
  engine: "BADGER"
  meta: "./test-data/cluster1/meta"
  wal: "./test-data/cluster1/wal"
  partitions:
  - "./test-data/cluster1/data/0"
  - "./test-data/cluster1/data/1"
  - "./test-data/cluster1/data/2"
log:
  level: 5
  path: "./test-data/cluster1/log"
