// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	DataCenter           int32    `protobuf:"varint,1,opt,name=DataCenter,proto3" json:"DataCenter,omitempty"`
	Area                 int32    `protobuf:"varint,2,opt,name=Area,proto3" json:"Area,omitempty"`
	Rack                 int32    `protobuf:"varint,3,opt,name=Rack,proto3" json:"Rack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetDataCenter() int32 {
	if m != nil {
		return m.DataCenter
	}
	return 0
}

func (m *Repository) GetArea() int32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Repository) GetRack() int32 {
	if m != nil {
		return m.Rack
	}
	return 0
}

type Partition struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Partition) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Storage struct {
	Partitions           []*Partition `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Namespace struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Table struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Repository)(nil), "proto.Repository")
	proto.RegisterType((*Partition)(nil), "proto.Partition")
	proto.RegisterType((*Storage)(nil), "proto.Storage")
	proto.RegisterType((*Namespace)(nil), "proto.Namespace")
	proto.RegisterType((*Table)(nil), "proto.Table")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xbb, 0x51, 0x3a, 0x8a, 0xc8, 0xe0, 0x21, 0x27, 0x59, 0x72, 0x5a, 0x10, 0xd6,
	0x7f, 0x47, 0x4f, 0xa2, 0x67, 0x91, 0xb8, 0x5f, 0x60, 0xda, 0x0e, 0x12, 0x34, 0x99, 0x90, 0xe6,
	0xa0, 0xdf, 0x5e, 0x9a, 0x56, 0xe9, 0xd1, 0x53, 0x5e, 0xde, 0xbc, 0x79, 0xbf, 0x81, 0xd3, 0x5e,
	0xbc, 0x97, 0xb0, 0x8f, 0x49, 0xb2, 0xa0, 0x2a, 0x8f, 0x39, 0x00, 0x58, 0x8e, 0x32, 0xba, 0x2c,
	0xe9, 0x1b, 0x2f, 0x01, 0x9e, 0x29, 0xd3, 0x13, 0x87, 0xcc, 0x49, 0x57, 0xdb, 0x6a, 0xa7, 0xec,
	0xca, 0x41, 0x84, 0xcd, 0x63, 0x62, 0xd2, 0x75, 0x99, 0x14, 0x3d, 0x79, 0x96, 0xfa, 0x0f, 0xdd,
	0xcc, 0xde, 0xa4, 0xcd, 0x2d, 0xb4, 0xaf, 0x94, 0xb2, 0xcb, 0x4e, 0x02, 0x9e, 0x41, 0xed, 0x86,
	0xa5, 0xac, 0x76, 0x03, 0x5e, 0x80, 0x72, 0x61, 0xe0, 0xaf, 0xa5, 0x65, 0xfe, 0x98, 0x07, 0x38,
	0x7e, 0xcb, 0x92, 0xe8, 0x9d, 0xf1, 0x06, 0x20, 0xfe, 0x6e, 0x8f, 0xba, 0xda, 0x36, 0xbb, 0x93,
	0xbb, 0xf3, 0xf9, 0xec, 0xfd, 0x5f, 0xad, 0x5d, 0x65, 0xcc, 0x35, 0xb4, 0x2f, 0xe4, 0x79, 0x8c,
	0xd4, 0xf3, 0x8a, 0xd7, 0x14, 0x1e, 0xc2, 0x26, 0x90, 0xe7, 0x82, 0x6b, 0x6d, 0xd1, 0xe6, 0x0a,
	0xd4, 0x81, 0xba, 0xcf, 0x7f, 0x85, 0xbb, 0xa3, 0x82, 0xbe, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0xba, 0x83, 0xc4, 0x41, 0x01, 0x00, 0x00,
}
