// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Key                  []byte   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMeta) Reset()         { *m = DataMeta{} }
func (m *DataMeta) String() string { return proto.CompactTextString(m) }
func (*DataMeta) ProtoMessage()    {}
func (*DataMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *DataMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMeta.Unmarshal(m, b)
}
func (m *DataMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMeta.Marshal(b, m, deterministic)
}
func (m *DataMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMeta.Merge(m, src)
}
func (m *DataMeta) XXX_Size() int {
	return xxx_messageInfo_DataMeta.Size(m)
}
func (m *DataMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DataMeta proto.InternalMessageInfo

func (m *DataMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataMeta) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DataMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DataMeta) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DataMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DataContent struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataContent) Reset()         { *m = DataContent{} }
func (m *DataContent) String() string { return proto.CompactTextString(m) }
func (*DataContent) ProtoMessage()    {}
func (*DataContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *DataContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataContent.Unmarshal(m, b)
}
func (m *DataContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataContent.Marshal(b, m, deterministic)
}
func (m *DataContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataContent.Merge(m, src)
}
func (m *DataContent) XXX_Size() int {
	return xxx_messageInfo_DataContent.Size(m)
}
func (m *DataContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DataContent.DiscardUnknown(m)
}

var xxx_messageInfo_DataContent proto.InternalMessageInfo

func (m *DataContent) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DataContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type DataBody struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ring                 int32    `protobuf:"varint,2,opt,name=ring,proto3" json:"ring,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Partition            int32    `protobuf:"varint,5,opt,name=partition,proto3" json:"partition,omitempty"`
	Version              int32    `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataBody) Reset()         { *m = DataBody{} }
func (m *DataBody) String() string { return proto.CompactTextString(m) }
func (*DataBody) ProtoMessage()    {}
func (*DataBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *DataBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBody.Unmarshal(m, b)
}
func (m *DataBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBody.Marshal(b, m, deterministic)
}
func (m *DataBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBody.Merge(m, src)
}
func (m *DataBody) XXX_Size() int {
	return xxx_messageInfo_DataBody.Size(m)
}
func (m *DataBody) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBody.DiscardUnknown(m)
}

var xxx_messageInfo_DataBody proto.InternalMessageInfo

func (m *DataBody) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DataBody) GetRing() int32 {
	if m != nil {
		return m.Ring
	}
	return 0
}

func (m *DataBody) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DataBody) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DataBody) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *DataBody) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PushRequest struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PullRequest struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

type PullResponse struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushPullRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPullRequest) Reset()         { *m = PushPullRequest{} }
func (m *PushPullRequest) String() string { return proto.CompactTextString(m) }
func (*PushPullRequest) ProtoMessage()    {}
func (*PushPullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *PushPullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPullRequest.Unmarshal(m, b)
}
func (m *PushPullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPullRequest.Marshal(b, m, deterministic)
}
func (m *PushPullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullRequest.Merge(m, src)
}
func (m *PushPullRequest) XXX_Size() int {
	return xxx_messageInfo_PushPullRequest.Size(m)
}
func (m *PushPullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullRequest proto.InternalMessageInfo

type PushPullResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPullResponse) Reset()         { *m = PushPullResponse{} }
func (m *PushPullResponse) String() string { return proto.CompactTextString(m) }
func (*PushPullResponse) ProtoMessage()    {}
func (*PushPullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *PushPullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPullResponse.Unmarshal(m, b)
}
func (m *PushPullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPullResponse.Marshal(b, m, deterministic)
}
func (m *PushPullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPullResponse.Merge(m, src)
}
func (m *PushPullResponse) XXX_Size() int {
	return xxx_messageInfo_PushPullResponse.Size(m)
}
func (m *PushPullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushPullResponse proto.InternalMessageInfo

type DataMigrateRequest struct {
	StartRing            int32    `protobuf:"varint,1,opt,name=startRing,proto3" json:"startRing,omitempty"`
	EndRing              int32    `protobuf:"varint,2,opt,name=endRing,proto3" json:"endRing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMigrateRequest) Reset()         { *m = DataMigrateRequest{} }
func (m *DataMigrateRequest) String() string { return proto.CompactTextString(m) }
func (*DataMigrateRequest) ProtoMessage()    {}
func (*DataMigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{9}
}

func (m *DataMigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMigrateRequest.Unmarshal(m, b)
}
func (m *DataMigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMigrateRequest.Marshal(b, m, deterministic)
}
func (m *DataMigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMigrateRequest.Merge(m, src)
}
func (m *DataMigrateRequest) XXX_Size() int {
	return xxx_messageInfo_DataMigrateRequest.Size(m)
}
func (m *DataMigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataMigrateRequest proto.InternalMessageInfo

func (m *DataMigrateRequest) GetStartRing() int32 {
	if m != nil {
		return m.StartRing
	}
	return 0
}

func (m *DataMigrateRequest) GetEndRing() int32 {
	if m != nil {
		return m.EndRing
	}
	return 0
}

type DataMigrateResponse struct {
	Completed            bool     `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMigrateResponse) Reset()         { *m = DataMigrateResponse{} }
func (m *DataMigrateResponse) String() string { return proto.CompactTextString(m) }
func (*DataMigrateResponse) ProtoMessage()    {}
func (*DataMigrateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{10}
}

func (m *DataMigrateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMigrateResponse.Unmarshal(m, b)
}
func (m *DataMigrateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMigrateResponse.Marshal(b, m, deterministic)
}
func (m *DataMigrateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMigrateResponse.Merge(m, src)
}
func (m *DataMigrateResponse) XXX_Size() int {
	return xxx_messageInfo_DataMigrateResponse.Size(m)
}
func (m *DataMigrateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMigrateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataMigrateResponse proto.InternalMessageInfo

func (m *DataMigrateResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*DataMeta)(nil), "proto.DataMeta")
	proto.RegisterType((*DataContent)(nil), "proto.DataContent")
	proto.RegisterType((*DataBody)(nil), "proto.DataBody")
	proto.RegisterType((*PushRequest)(nil), "proto.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "proto.PushResponse")
	proto.RegisterType((*PullRequest)(nil), "proto.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "proto.PullResponse")
	proto.RegisterType((*PushPullRequest)(nil), "proto.PushPullRequest")
	proto.RegisterType((*PushPullResponse)(nil), "proto.PushPullResponse")
	proto.RegisterType((*DataMigrateRequest)(nil), "proto.DataMigrateRequest")
	proto.RegisterType((*DataMigrateResponse)(nil), "proto.DataMigrateResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6e, 0xea, 0x30,
	0x10, 0xc6, 0x15, 0x20, 0x40, 0x06, 0xf4, 0xe0, 0xb9, 0x5d, 0x64, 0x91, 0x45, 0x94, 0x6e, 0xb2,
	0x62, 0x01, 0x27, 0xe8, 0x9f, 0x65, 0x2b, 0x55, 0xbe, 0x81, 0x49, 0x46, 0x34, 0x6a, 0xb0, 0xd3,
	0x78, 0xa8, 0x44, 0xcf, 0xd5, 0x03, 0x56, 0xb6, 0xe3, 0x26, 0xec, 0xda, 0xae, 0xe2, 0x6f, 0x9c,
	0xf9, 0xe6, 0xe7, 0x99, 0x01, 0x28, 0x05, 0x89, 0x4d, 0xd3, 0x2a, 0x52, 0x2c, 0xb4, 0x9f, 0xec,
	0x03, 0xe6, 0x0f, 0x82, 0xc4, 0x13, 0x92, 0x60, 0x31, 0xcc, 0xde, 0xb1, 0xd5, 0x95, 0x92, 0x71,
	0x90, 0x06, 0x79, 0xc8, 0xbd, 0x64, 0xff, 0x60, 0x54, 0x95, 0xf1, 0x28, 0x0d, 0xf2, 0x25, 0x1f,
	0x55, 0x25, 0x4b, 0x20, 0x92, 0xe2, 0x88, 0xba, 0x11, 0x05, 0xc6, 0xe3, 0x34, 0xc8, 0x23, 0xde,
	0x07, 0xd8, 0x35, 0x84, 0x24, 0xf6, 0x35, 0xc6, 0x13, 0x7b, 0xe3, 0x04, 0x5b, 0xc3, 0xf8, 0x15,
	0xcf, 0x71, 0x68, 0x4d, 0xcc, 0x31, 0xbb, 0x85, 0x85, 0xa9, 0x7d, 0xaf, 0x24, 0xa1, 0x24, 0x53,
	0xbe, 0xc4, 0x1a, 0x09, 0x4b, 0x5b, 0x7e, 0xce, 0xbd, 0x34, 0x37, 0x85, 0xfb, 0xa9, 0x63, 0xf0,
	0x32, 0xfb, 0x0c, 0x1c, 0xff, 0x9d, 0x2a, 0xcf, 0x1d, 0x65, 0xf0, 0x4d, 0xc9, 0x60, 0xd2, 0x56,
	0xf2, 0x60, 0x73, 0x42, 0x6e, 0xcf, 0x7f, 0x22, 0x4f, 0x20, 0x6a, 0x44, 0x4b, 0x15, 0x99, 0xce,
	0x84, 0xd6, 0xac, 0x0f, 0x0c, 0xbb, 0x36, 0xbd, 0xec, 0xda, 0x00, 0x7b, 0x76, 0x89, 0xbd, 0x85,
	0xc5, 0xf3, 0x49, 0xbf, 0x70, 0x7c, 0x3b, 0xa1, 0x26, 0x76, 0x03, 0x13, 0x33, 0x99, 0x38, 0x48,
	0xc7, 0xf9, 0x62, 0xbb, 0x72, 0x13, 0xda, 0xf8, 0x77, 0x71, 0x7b, 0x99, 0xe5, 0xb0, 0x74, 0x39,
	0xba, 0x51, 0x52, 0xa3, 0x71, 0xd7, 0xa7, 0xa2, 0x40, 0xad, 0x7d, 0xbb, 0x3a, 0xe9, 0xdc, 0xeb,
	0xfa, 0x57, 0xee, 0x3b, 0xe3, 0x6e, 0x72, 0x3a, 0xf7, 0x1f, 0x25, 0xfd, 0x87, 0x95, 0x41, 0x1a,
	0x14, 0xcb, 0x18, 0xac, 0xfb, 0x90, 0xf3, 0xca, 0x1e, 0x81, 0xd9, 0x1d, 0xab, 0x0e, 0xad, 0x20,
	0xf4, 0x58, 0x09, 0x44, 0x9a, 0x44, 0x4b, 0xdc, 0x8c, 0xc8, 0xed, 0x5b, 0x1f, 0x30, 0xaf, 0x43,
	0x59, 0xf2, 0x7e, 0x7c, 0x5e, 0x66, 0x3b, 0xb8, 0xba, 0x70, 0xeb, 0x80, 0x13, 0x88, 0x0a, 0x75,
	0x6c, 0x86, 0xfb, 0xd3, 0x07, 0xf6, 0x53, 0xcb, 0xbf, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x16,
	0x84, 0x4e, 0x39, 0x02, 0x03, 0x00, 0x00,
}
