// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMeta) Reset()         { *m = DataMeta{} }
func (m *DataMeta) String() string { return proto.CompactTextString(m) }
func (*DataMeta) ProtoMessage()    {}
func (*DataMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *DataMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMeta.Unmarshal(m, b)
}
func (m *DataMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMeta.Marshal(b, m, deterministic)
}
func (m *DataMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMeta.Merge(m, src)
}
func (m *DataMeta) XXX_Size() int {
	return xxx_messageInfo_DataMeta.Size(m)
}
func (m *DataMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DataMeta proto.InternalMessageInfo

func (m *DataMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataMeta) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type DataContent struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataContent) Reset()         { *m = DataContent{} }
func (m *DataContent) String() string { return proto.CompactTextString(m) }
func (*DataContent) ProtoMessage()    {}
func (*DataContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *DataContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataContent.Unmarshal(m, b)
}
func (m *DataContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataContent.Marshal(b, m, deterministic)
}
func (m *DataContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataContent.Merge(m, src)
}
func (m *DataContent) XXX_Size() int {
	return xxx_messageInfo_DataContent.Size(m)
}
func (m *DataContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DataContent.DiscardUnknown(m)
}

var xxx_messageInfo_DataContent proto.InternalMessageInfo

func (m *DataContent) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DataContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type DataDesc struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDesc) Reset()         { *m = DataDesc{} }
func (m *DataDesc) String() string { return proto.CompactTextString(m) }
func (*DataDesc) ProtoMessage()    {}
func (*DataDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *DataDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDesc.Unmarshal(m, b)
}
func (m *DataDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDesc.Marshal(b, m, deterministic)
}
func (m *DataDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDesc.Merge(m, src)
}
func (m *DataDesc) XXX_Size() int {
	return xxx_messageInfo_DataDesc.Size(m)
}
func (m *DataDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDesc.DiscardUnknown(m)
}

var xxx_messageInfo_DataDesc proto.InternalMessageInfo

func (m *DataDesc) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataDesc) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type DataBody struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataBody) Reset()         { *m = DataBody{} }
func (m *DataBody) String() string { return proto.CompactTextString(m) }
func (*DataBody) ProtoMessage()    {}
func (*DataBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *DataBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBody.Unmarshal(m, b)
}
func (m *DataBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBody.Marshal(b, m, deterministic)
}
func (m *DataBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBody.Merge(m, src)
}
func (m *DataBody) XXX_Size() int {
	return xxx_messageInfo_DataBody.Size(m)
}
func (m *DataBody) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBody.DiscardUnknown(m)
}

var xxx_messageInfo_DataBody proto.InternalMessageInfo

func (m *DataBody) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataBody) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PushRequest struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushResponse struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

type PullRequest struct {
	Data                 []*DataDesc `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetData() []*DataDesc {
	if m != nil {
		return m.Data
	}
	return nil
}

type PullResponse struct {
	Data                 []*DataBody `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetData() []*DataBody {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DataMeta)(nil), "proto.DataMeta")
	proto.RegisterType((*DataContent)(nil), "proto.DataContent")
	proto.RegisterType((*DataDesc)(nil), "proto.DataDesc")
	proto.RegisterType((*DataBody)(nil), "proto.DataBody")
	proto.RegisterType((*PushRequest)(nil), "proto.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "proto.PushResponse")
	proto.RegisterType((*PullRequest)(nil), "proto.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "proto.PullResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0xd6, 0x6a, 0x99, 0x2d, 0x0a, 0x39, 0xe5, 0xb8, 0xc4, 0xcb, 0x9e, 0x7a, 0x68,
	0x7d, 0x01, 0xb5, 0x57, 0x45, 0xf2, 0x06, 0xb1, 0x19, 0x70, 0x61, 0x49, 0x6a, 0x33, 0x15, 0x7c,
	0x7b, 0x99, 0xa4, 0x81, 0xed, 0xc9, 0xed, 0x69, 0x99, 0x9d, 0x7c, 0xf3, 0xfd, 0xfc, 0x00, 0xde,
	0x91, 0x5b, 0x1f, 0x8e, 0x91, 0xa2, 0x5a, 0xe4, 0x8f, 0x79, 0x82, 0xe5, 0xce, 0x91, 0x7b, 0x43,
	0x72, 0x4a, 0xc3, 0xdd, 0x0f, 0x1e, 0xd3, 0x10, 0x83, 0x16, 0x9d, 0xe8, 0x17, 0xb6, 0x8e, 0xea,
	0x1e, 0xe4, 0xe0, 0xb5, 0xec, 0x44, 0xbf, 0xb2, 0x72, 0xf0, 0xe6, 0x19, 0x5a, 0xa6, 0x5e, 0x63,
	0x20, 0x0c, 0xc4, 0xa0, 0xc7, 0x11, 0x09, 0x7d, 0x06, 0x97, 0xb6, 0x8e, 0xbc, 0xd9, 0x97, 0x47,
	0x67, 0xba, 0x8e, 0x55, 0xbc, 0xc3, 0xb4, 0x3f, 0x9f, 0x67, 0xb4, 0xe1, 0xf3, 0xd3, 0x20, 0xf2,
	0x22, 0x88, 0x79, 0x2f, 0xd4, 0x4b, 0xf4, 0xbf, 0xf3, 0xa9, 0x69, 0x8a, 0xe6, 0x32, 0xc5, 0x06,
	0xda, 0x8f, 0x53, 0xfa, 0xb2, 0xf8, 0x7d, 0xc2, 0x44, 0xea, 0x11, 0x6e, 0xb8, 0x22, 0x2d, 0xba,
	0xa6, 0x6f, 0x37, 0x0f, 0xa5, 0xaa, 0x75, 0x35, 0xda, 0xbc, 0x34, 0x5b, 0x58, 0x15, 0x26, 0x1d,
	0x62, 0x48, 0x38, 0x0f, 0xca, 0xa2, 0x71, 0xfc, 0x5f, 0xc4, 0x85, 0x4c, 0x45, 0xcc, 0x5c, 0x21,
	0xfa, 0xbc, 0xcd, 0x7f, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xa4, 0x3c, 0x93, 0xec,
	0x01, 0x00, 0x00,
}
