// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataMeta struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Repository           *Repository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Partition            *Partition  `protobuf:"bytes,3,opt,name=partition,proto3" json:"partition,omitempty"`
	History              []*DataDesc `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataMeta) Reset()         { *m = DataMeta{} }
func (m *DataMeta) String() string { return proto.CompactTextString(m) }
func (*DataMeta) ProtoMessage()    {}
func (*DataMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *DataMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMeta.Unmarshal(m, b)
}
func (m *DataMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMeta.Marshal(b, m, deterministic)
}
func (m *DataMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMeta.Merge(m, src)
}
func (m *DataMeta) XXX_Size() int {
	return xxx_messageInfo_DataMeta.Size(m)
}
func (m *DataMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DataMeta proto.InternalMessageInfo

func (m *DataMeta) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataMeta) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *DataMeta) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *DataMeta) GetHistory() []*DataDesc {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*DataMeta)(nil), "proto.DataMeta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2d, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x3c, 0xc9, 0xf9, 0xb9, 0xb9,
	0xf9, 0x79, 0x10, 0x41, 0x29, 0xae, 0x94, 0x44, 0x98, 0x02, 0xa5, 0x15, 0x8c, 0x5c, 0x1c, 0x2e,
	0x89, 0x25, 0x89, 0xbe, 0xa9, 0x25, 0x89, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x86, 0x5c, 0x5c, 0x45, 0xa9, 0x05, 0xf9, 0xc5,
	0x99, 0x25, 0xf9, 0x45, 0x95, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x82, 0x10, 0x8d, 0x7a,
	0x41, 0x70, 0x89, 0x20, 0x24, 0x45, 0x42, 0x7a, 0x5c, 0x9c, 0x05, 0x89, 0x45, 0x25, 0x99, 0x25,
	0x99, 0xf9, 0x79, 0x12, 0xcc, 0x60, 0x1d, 0x02, 0x50, 0x1d, 0x01, 0x30, 0xf1, 0x20, 0x84, 0x12,
	0x21, 0x4d, 0x2e, 0xf6, 0x8c, 0xcc, 0x62, 0xb0, 0xf9, 0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xfc,
	0x50, 0xd5, 0x20, 0x47, 0xb9, 0xa4, 0x16, 0x27, 0x07, 0xc1, 0xe4, 0x93, 0xd8, 0xc0, 0x12, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x7e, 0x39, 0x67, 0xe0, 0x00, 0x00, 0x00,
}
