// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClusterHealth int32

const (
	ClusterHealth_CH_Unknown       ClusterHealth = 0
	ClusterHealth_CH_Normal        ClusterHealth = 1
	ClusterHealth_CH_Unavailable   ClusterHealth = 2
	ClusterHealth_CH_NotInitialize ClusterHealth = 3
	ClusterHealth_CH_NotSafe       ClusterHealth = 4
)

var ClusterHealth_name = map[int32]string{
	0: "CH_Unknown",
	1: "CH_Normal",
	2: "CH_Unavailable",
	3: "CH_NotInitialize",
	4: "CH_NotSafe",
}

var ClusterHealth_value = map[string]int32{
	"CH_Unknown":       0,
	"CH_Normal":        1,
	"CH_Unavailable":   2,
	"CH_NotInitialize": 3,
	"CH_NotSafe":       4,
}

func (x ClusterHealth) String() string {
	return proto.EnumName(ClusterHealth_name, int32(x))
}

func (ClusterHealth) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

type NodeHealth int32

const (
	NodeHealth_Suspect NodeHealth = 0
	NodeHealth_Alive   NodeHealth = 1
	NodeHealth_Dead    NodeHealth = 2
)

var NodeHealth_name = map[int32]string{
	0: "Suspect",
	1: "Alive",
	2: "Dead",
}

var NodeHealth_value = map[string]int32{
	"Suspect": 0,
	"Alive":   1,
	"Dead":    2,
}

func (x NodeHealth) String() string {
	return proto.EnumName(NodeHealth_name, int32(x))
}

func (NodeHealth) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

type NodeStatus int32

const (
	NodeStatus_Unknown     NodeStatus = 0
	NodeStatus_Normal      NodeStatus = 1
	NodeStatus_Unavailable NodeStatus = 2
	NodeStatus_New         NodeStatus = 3
	NodeStatus_Recovering  NodeStatus = 4
)

var NodeStatus_name = map[int32]string{
	0: "Unknown",
	1: "Normal",
	2: "Unavailable",
	3: "New",
	4: "Recovering",
}

var NodeStatus_value = map[string]int32{
	"Unknown":     0,
	"Normal":      1,
	"Unavailable": 2,
	"New":         3,
	"Recovering":  4,
}

func (x NodeStatus) String() string {
	return proto.EnumName(NodeStatus_name, int32(x))
}

func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

type Node struct {
	Id                   int32       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string      `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32       `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Repository           *Repository `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`
	Health               NodeHealth  `protobuf:"varint,7,opt,name=health,proto3,enum=proto.NodeHealth" json:"health,omitempty"`
	Status               NodeStatus  `protobuf:"varint,8,opt,name=status,proto3,enum=proto.NodeStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *Node) GetHealth() NodeHealth {
	if m != nil {
		return m.Health
	}
	return NodeHealth_Suspect
}

func (m *Node) GetStatus() NodeStatus {
	if m != nil {
		return m.Status
	}
	return NodeStatus_Unknown
}

func init() {
	proto.RegisterEnum("proto.ClusterHealth", ClusterHealth_name, ClusterHealth_value)
	proto.RegisterEnum("proto.NodeHealth", NodeHealth_name, NodeHealth_value)
	proto.RegisterEnum("proto.NodeStatus", NodeStatus_name, NodeStatus_value)
	proto.RegisterType((*Node)(nil), "proto.Node")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0x71, 0x48, 0xf8, 0x33, 0x2c, 0x59, 0xef, 0x68, 0x0f, 0xd1, 0x9e, 0xa2, 0x3d, 0xa5,
	0x1c, 0x90, 0xda, 0x3e, 0x41, 0x45, 0x0f, 0xf4, 0x92, 0x4a, 0x46, 0x3d, 0x23, 0x43, 0xa6, 0xc5,
	0xaa, 0xb1, 0x23, 0xc7, 0x80, 0xda, 0xd7, 0xeb, 0x8b, 0x55, 0x38, 0x08, 0x5a, 0xf5, 0x64, 0xcf,
	0x7c, 0x3f, 0x7d, 0xfa, 0x69, 0x00, 0x8c, 0xad, 0x68, 0x5a, 0x3b, 0xeb, 0x2d, 0x26, 0xe1, 0xf9,
	0xf7, 0x6b, 0x6d, 0xb7, 0x5b, 0x6b, 0xda, 0xe5, 0xff, 0x0f, 0x06, 0x71, 0x69, 0x2b, 0xc2, 0x14,
	0x22, 0x55, 0x65, 0x51, 0xce, 0x8a, 0x44, 0x44, 0xaa, 0x0a, 0x73, 0x9d, 0x75, 0x73, 0x56, 0x0c,
	0x45, 0xa4, 0x6a, 0x44, 0x88, 0x6b, 0xeb, 0x7c, 0x16, 0x07, 0x22, 0xfc, 0xf1, 0x1a, 0xc0, 0x51,
	0x6d, 0x1b, 0xe5, 0xad, 0x7b, 0xcb, 0x92, 0x9c, 0x15, 0xa3, 0x9b, 0x3f, 0x6d, 0xf1, 0x54, 0x9c,
	0x03, 0xf1, 0x05, 0xc2, 0x2b, 0xe8, 0x6d, 0x48, 0x6a, 0xbf, 0xc9, 0xfa, 0x39, 0x2b, 0xd2, 0x33,
	0x7e, 0x74, 0x98, 0x87, 0x40, 0x9c, 0x80, 0x23, 0xda, 0x78, 0xe9, 0x77, 0x4d, 0x36, 0xf8, 0x81,
	0x2e, 0x42, 0x20, 0x4e, 0xc0, 0x64, 0x03, 0xe3, 0x99, 0xde, 0x35, 0x9e, 0x5c, 0xdb, 0x81, 0x29,
	0xc0, 0x6c, 0xbe, 0x7c, 0x32, 0xaf, 0xc6, 0x1e, 0x0c, 0xef, 0xe0, 0x18, 0x86, 0xb3, 0xf9, 0xb2,
	0xb4, 0x6e, 0x2b, 0x35, 0x67, 0x88, 0x90, 0x86, 0x58, 0xee, 0xa5, 0xd2, 0x72, 0xa5, 0x89, 0x47,
	0xf8, 0x17, 0x78, 0x40, 0xfc, 0x83, 0x51, 0x5e, 0x49, 0xad, 0xde, 0x89, 0x77, 0x4f, 0x45, 0xa5,
	0xf5, 0x0b, 0xf9, 0x4c, 0x3c, 0x9e, 0x4c, 0x01, 0x2e, 0xaa, 0x38, 0x82, 0xfe, 0x62, 0xd7, 0xd4,
	0xb4, 0xf6, 0xbc, 0x83, 0x43, 0x48, 0xee, 0xb4, 0xda, 0x13, 0x67, 0x38, 0x80, 0xf8, 0x9e, 0x64,
	0xc5, 0xa3, 0xc9, 0x63, 0xcb, 0xb7, 0xbe, 0x47, 0xfe, 0xe2, 0x04, 0xd0, 0x3b, 0x0b, 0xfd, 0x86,
	0xd1, 0x77, 0x9b, 0x3e, 0x74, 0x4b, 0x3a, 0xb4, 0x02, 0x82, 0xd6, 0x76, 0x4f, 0x4e, 0x99, 0x17,
	0x1e, 0xaf, 0x7a, 0xe1, 0x08, 0xb7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x1c, 0xe6, 0x65,
	0xda, 0x01, 0x00, 0x00,
}
