// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketMode int32

const (
	PacketMode_TCP       PacketMode = 0
	PacketMode_UDP       PacketMode = 1
	PacketMode_HTTP      PacketMode = 2
	PacketMode_Multicast PacketMode = 3
	PacketMode_Broadcast PacketMode = 4
)

var PacketMode_name = map[int32]string{
	0: "TCP",
	1: "UDP",
	2: "HTTP",
	3: "Multicast",
	4: "Broadcast",
}

var PacketMode_value = map[string]int32{
	"TCP":       0,
	"UDP":       1,
	"HTTP":      2,
	"Multicast": 3,
	"Broadcast": 4,
}

func (x PacketMode) String() string {
	return proto.EnumName(PacketMode_name, int32(x))
}

func (PacketMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

type PacketType int32

const (
	PacketType_SystemHi         PacketType = 0
	PacketType_DataPush         PacketType = 1001
	PacketType_DataPushReply    PacketType = 1002
	PacketType_DataPull         PacketType = 1003
	PacketType_DataPullReply    PacketType = 1004
	PacketType_DataMigrate      PacketType = 1005
	PacketType_DataMigrateReply PacketType = 1006
)

var PacketType_name = map[int32]string{
	0:    "SystemHi",
	1001: "DataPush",
	1002: "DataPushReply",
	1003: "DataPull",
	1004: "DataPullReply",
	1005: "DataMigrate",
	1006: "DataMigrateReply",
}

var PacketType_value = map[string]int32{
	"SystemHi":         0,
	"DataPush":         1001,
	"DataPushReply":    1002,
	"DataPull":         1003,
	"DataPullReply":    1004,
	"DataMigrate":      1005,
	"DataMigrateReply": 1006,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}

type Packet struct {
	Version              int32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Mode                 PacketMode `protobuf:"varint,3,opt,name=mode,proto3,enum=proto.PacketMode" json:"mode,omitempty"`
	Type                 PacketType `protobuf:"varint,4,opt,name=type,proto3,enum=proto.PacketType" json:"type,omitempty"`
	From                 int32      `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32      `protobuf:"varint,6,opt,name=to,proto3" json:"to,omitempty"`
	Receivers            []int32    `protobuf:"varint,7,rep,packed,name=receivers,proto3" json:"receivers,omitempty"`
	Content              []byte     `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Packet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Packet) GetMode() PacketMode {
	if m != nil {
		return m.Mode
	}
	return PacketMode_TCP
}

func (m *Packet) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_SystemHi
}

func (m *Packet) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Packet) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Packet) GetReceivers() []int32 {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *Packet) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.PacketMode", PacketMode_name, PacketMode_value)
	proto.RegisterEnum("proto.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*Packet)(nil), "proto.Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x6a, 0xfb, 0x30,
	0x10, 0xc5, 0x23, 0x7f, 0x44, 0xce, 0xfc, 0x93, 0xa0, 0xff, 0x40, 0x41, 0x8b, 0x2e, 0x4c, 0xa1,
	0x60, 0xb2, 0xc8, 0xa2, 0xbd, 0x41, 0x1b, 0x4a, 0x36, 0x01, 0xa3, 0xba, 0x07, 0x70, 0x6d, 0xb5,
	0x15, 0x75, 0x22, 0x63, 0x2b, 0x05, 0x1f, 0xa1, 0x77, 0xec, 0x05, 0xfa, 0x79, 0x86, 0x22, 0x19,
	0x93, 0x2c, 0xba, 0xd2, 0xbc, 0x37, 0x3f, 0xde, 0x3c, 0x04, 0xd3, 0x3a, 0x2f, 0x9e, 0xa5, 0x59,
	0xd6, 0x8d, 0x36, 0x1a, 0x43, 0xf7, 0x9c, 0xbd, 0x11, 0x18, 0xa7, 0xce, 0x47, 0x0e, 0xf4, 0x45,
	0x36, 0xad, 0xd2, 0x3b, 0x4e, 0x62, 0x92, 0x84, 0x62, 0x90, 0x38, 0x07, 0x4f, 0x95, 0xdc, 0x8b,
	0x49, 0x32, 0x11, 0x9e, 0x2a, 0xf1, 0x1c, 0x82, 0xad, 0x2e, 0x25, 0xf7, 0x63, 0x92, 0xcc, 0x2f,
	0xfe, 0xf7, 0x89, 0xcb, 0x3e, 0x66, 0xa3, 0x4b, 0x29, 0xdc, 0xda, 0x62, 0xa6, 0xab, 0x25, 0x0f,
	0xfe, 0xc0, 0xb2, 0xae, 0x96, 0xc2, 0xad, 0x11, 0x21, 0x78, 0x68, 0xf4, 0x96, 0x87, 0xee, 0xa8,
	0x9b, 0xed, 0x45, 0xa3, 0xf9, 0xd8, 0x39, 0x9e, 0xd1, 0x78, 0x0a, 0x93, 0x46, 0x16, 0x52, 0xd9,
	0x46, 0x9c, 0xc6, 0x7e, 0x12, 0x8a, 0x83, 0x61, 0x9b, 0x17, 0x7a, 0x67, 0xe4, 0xce, 0xf0, 0x28,
	0x26, 0xc9, 0x54, 0x0c, 0x72, 0x71, 0x03, 0x70, 0xa8, 0x85, 0x14, 0xfc, 0xec, 0x3a, 0x65, 0x23,
	0x3b, 0xdc, 0xad, 0x52, 0x46, 0x30, 0x82, 0x60, 0x9d, 0x65, 0x29, 0xf3, 0x70, 0x06, 0x93, 0xcd,
	0xbe, 0x32, 0xaa, 0xc8, 0x5b, 0xc3, 0x7c, 0x2b, 0xaf, 0x1a, 0x9d, 0x97, 0x4e, 0x06, 0x8b, 0x57,
	0x32, 0x04, 0xd9, 0xe2, 0x38, 0x85, 0xe8, 0xb6, 0x6b, 0x8d, 0xdc, 0xae, 0x15, 0x1b, 0xe1, 0x0c,
	0xa2, 0x55, 0x6e, 0xf2, 0x74, 0xdf, 0x3e, 0xb1, 0x77, 0x8a, 0x08, 0xb3, 0x41, 0x0a, 0x59, 0x57,
	0x1d, 0xfb, 0xa0, 0x07, 0xa4, 0xaa, 0xd8, 0xe7, 0x11, 0x52, 0x55, 0x3d, 0xf2, 0x45, 0x91, 0xc1,
	0x3f, 0xeb, 0x6d, 0xd4, 0x63, 0x93, 0x1b, 0xc9, 0xbe, 0x29, 0x9e, 0x00, 0x3b, 0x72, 0x7a, 0xf0,
	0x87, 0xde, 0x8f, 0xdd, 0x3f, 0x5e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x6b, 0x71, 0x95,
	0xd0, 0x01, 0x00, 0x00,
}
